# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b43de58264a28b9f139169fb2112ca06959ac1aff18dd53190d7115fa76462e379eae4a2ce575715d6b9d962471673cbb13d617c32a0bb7fff542acbfa92eb3

test:
  secret_key_base: 47e6a7fcbbef8b56b5c38e2babfec3d3c20a837c086c1bb6fe6561435431ee0e553eeebb0facbf42497f5a31151bb296d673aa38fab3b327a127c8e1633768f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
